---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thing-service
  annotations:
    iam.gke.io/gcp-service-account: thing-service@kinetic-dryad-364616.iam.gserviceaccount.com

# gcloud iam service-accounts create thing-service \
#   --description="Manage resources for thing-service" \
#   --display-name="Thing Service"

# gcloud iam service-accounts add-iam-policy-binding \
#   --role="roles/iam.workloadIdentityUser" \
#   --member="serviceAccount:kinetic-dryad-364616.svc.id.goog[develop/thing-service]" \
#   thing-service@kinetic-dryad-364616.iam.gserviceaccount.com

# gcloud sql databases create things --instance=thing-service-db
